# This is a basic workflow to help you get started with Actions

name: CICD Example


# Triggers the workflow on push or pull request events but only for the master branch
on:
  push:
    branches: [ master ]

  workflow_dispatch: